### ISSUE TITLE
Beam::Emitter is not "Clean" and pollutes all roles

### ISSUE THREAD

**Issue by kentfredric** [preaction/Beam-Emitter#13]
Types::Standard is used in this Role, and all the types declared by Beam::Emitter turn up
on composed classes:

https://metacpan.org/source/PREACTION/Beam-Emitter-1.002/lib/Beam/Emitter.pm#L9

![snapshot_20160910_070801](https://cloud.githubusercontent.com/assets/44790/18399503/6ee81d66-7725-11e6-89ab-028c80ddd06e.png)
![snapshot_20160910_070826](https://cloud.githubusercontent.com/assets/44790/18399507/75bba4e6-7725-11e6-9a00-35a5e8df9de9.png)

This also means Beam::Emitter can be induced to cause Role conflicts:

``` perl
#!perl
use strict;
use warnings;

{
  package Hateful::Role;
  use Moose::Role;

  sub Bool { }
}

{
  package Self::Abuse;
  use Moose;
  with "Hateful::Role","Beam::Emitter";

}

```

```
Due to a method name conflict in roles 'Beam::Emitter' and 'Hateful::Role', the method 'Bool' must be implemented or excluded by 'Self::Abuse' at /home/kent/perl5/perlbrew/perls/5.25.4-nossp-sdbm-nopmc/lib/site_perl/5.25.4/x86_64-linux/Moose/Exporter.pm line 419
    Moose::with('Hateful::Role', 'Beam::Emitter') called at /tmp/beamyfail.pl line 15
```

The only good news is that this happening accidentally is unlikely, because synthetic tests with roles using MooseX::Types or Types::Standard are not sufficient to cause a conflict.

**Comment by kentfredric** [comment]
Locally poking the code shows that relocating the `use Moo::Role` line further down changes what `Moo` considers part of the exported role API.

However, doing 

```diff
-use Types::Standard qw(:all);
+use Types::Standard qw( HashRef );
```

```perl
no Moo::Role;
no Types::Standard
```

at the right places tighten it up a bit better.

This leaves us with

![snapshot_20160910_072541](https://cloud.githubusercontent.com/assets/44790/18399956/ceed0c88-7727-11e6-9070-7a7b493f4442.png)

Of which only `croak` and `weaken` are left to be cleaned up.

**Comment by preaction** [comment]
The Moo docs (http://search.cpan.org/~haarg/Moo-2.002005/lib/Moo.pm#CLEANING_UP_IMPORTS) seem to indicate all we have to do now is just import everything _before_ importing Moo::Role, so this should be easy! I'll get to this change (and some corresponding regression tests) before the next release.
