### ISSUE TITLE
on and un aliases provide inconsistent behavior under method modifiers.

### ISSUE THREAD

**Issue by djerius** [preaction/Beam-Emitter#18]
`Beam::Emitter` uses  Perl symbol table aliases to alias `on` and `un` to `subscribe` and `unsubscribe`, but this foils method modifiers. 

For example.  Here's code which modifies subscribe:

```
  use 5.10.0;

  package P1 {

      use Moo::Role;
      sub subscribe { say ref $_[0], ": subscribe" }
      use subs qw[ on ];
     *on = \&subscribe;
  }

  package M1 {
      use Moo;
      with 'P1';

      before subscribe => sub { say ref $_[0], ": before subscribe" };
  }

  say;
  say "M1->on:";
  M1->new->on();
  say "M1->subscribe:";
  M1->new->subscribe();
```

This results in
```
M1->on:
M1: subscribe
M1->subscribe:
M1: before subscribe
M1: subscribe
```
Notice that the modified version of `subscribe` is not invoked by the `on` method.

Changing `on` so that it uses object method lookup works better:

```
package P2 {

    use Moo::Role;
    sub subscribe { say ref $_[0], "subscribe" }
    use subs qw[ on ];

    sub on {
	my $self = shift;
	$self->subscribe( @_ );
    }
}

package M2 {
    use Moo;
    with 'P2';

    before subscribe => sub { say ref $_[0], ": before subscribe" };
}

say;
say "M2->on:";
M2->new->on();
say "M2->subscribe:";
M2->new->subscribe();

```
results in
```
M2->on:
M2: before subscribe
M2: subscribe
M2->subscribe:
M2: before subscribe
M2: subscribe
```
but if  `on` is modified rather than `subscribe`, `subscribe` doesn't know about that:

```
package M3 {
    use Moo;
    with 'P2';

    before on => sub { say ref $_[0], ": before on" };
}

say;
say "M3->on:";
M3->new->on();
say "M3->subscribe:";
M3->new->subscribe();
```
results in:

```
M3->on:
M3: before on
M3: subscribe
M3->subscribe:
M3: subscribe
```

And this is just nuts:

```
package M4 {
    use Moo;
    with 'P2';

    before on => sub { say ref $_[0], ": before on" };
    before subscribe => sub { say ref $_[0], ": before subscribe" };
}

say;

say "M4->on:";
M4->new->on();

say "M4->subscribe:";
M4->new->subscribe();
```
which results in:

```
M4->on:
M4: before on
M4: before subscribe
M4: subscribe
M4->subscribe:
M4: before subscribe
M4: subscribe
```

I don't know any way of making this symmetric

**Comment by preaction** [comment]
Ouch. I think the best way forward is to make `on` and `un` do the method lookup like you mention, and then ensure that the documentation tells people to _never_ modify those aliases in composing/extending classes. It still leaves open the bug of wrapping/modifying `on` and `un`, but historical reasons mean we can't really fix this by removing the "convenience" aliases and just going with `on` and `unsubscribe` or something...

**Comment by preaction** [comment]
Did you want me to pick this up before the release, or did you want to give it a go? I'm planning on releasing once I get your two ready PRs merged and once this is addressed by either you or me.

**Comment by djerius** [comment]
I'm a bit pressed for time at the moment (despite the flurry of PR's) , so I'd be more than happy if you took care of it.

**Comment by preaction** [comment]
Can do, no big. Just didn't want to step on your toes ;) I'll tag this release tonight then, thanks for all your help!
